### ISSUE TITLE
PHP_Depend-beta

### ISSUE THREAD

**Issue by develnk** [djoos-cookbooks/pdepend#1]
pdepend/recipes/pear.rb
Line:26
PHP_Depend-beta is not exists. Now available PHP_Depend package.

**Comment by djoos** [comment]
Hi @develnk,

thanks for getting in touch!

PHP_Depend is the package used in the pear-recipe... Would you be able to give me some more background information on the issue you are experiencing?

Thanks in advance!

Kind regards,
David

**Comment by develnk** [comment]
Hi @djoos.

There is string in your recipe:
php_pear "PHP_Depend-beta" do

What equivalent to execute this code in console:
pear install pdepend/PHP_Depend-beta

But pdepend/PHP_Depend-beta is not exists now. This package now called pdepend/PHP_Depend (without "beta"). Becase of this i could not install phpmd cookbook.

**Comment by ghost** [comment]
Hi,

hmmm - could you let me know which version of the pdepend cookbook you're using?

1.0.0 is not making use of the "-beta" package name...

Thanks in advance!

Kind regards,
David=

**Comment by develnk** [comment]
So what is the problem. I get this cookbook from https://supermarket.chef.io/cookbooks/pdepend and there cookbook latest version is 0.0.4
I use librarian-chef and it downloads all contribution cookboks from https://supermarket.chef.io/cookbooks

Probably you need to update this cookbook on https://supermarket.chef.io/cookbooks/pdepend

Thanks.

**Comment by ghost** [comment]
Hi there,

it seems the latest dev version of the cookbook hasn't been published...

I'll get that sorted!

**Comment by djoos** [comment]
Hi @develnk,

I've just released version 1.0.0 on the Opscode community cookbook site / supermarket...

Hope this helps!

Kind regards,
David
